version: "3.8"

services:
  nodejs-app1:
    build:
      context: ./nodejs-app1
    ports:
      - "3001:3000"
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=

  nodejs-app2:
    build:
      context: ./nodejs-app2
    ports:
      - "3002:3000"
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=

  python-app1:
    build:
      context: ./python-app1
    ports:
      - "8001:8000"

  python-app2:
    build:
      context: ./python-app2
    ports:
      - "8002:8000"
